# Simple workflow for deploying static content to GitHub Pages
name: Deploy DocC

on:
  # Runs on pushes targeting the default branch
  release: {}
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  PLATFORM_IOS: generic/platform=iOS
  PLATFORM_MACOS: platform=macOS
  DOCC_PATH_IOS: Debug-iphoneos
  DOCC_PATH_MACOS: Debug

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Switch Xcode 🔄
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app
      - name: Build DocC Archive
        run: |
          xcodebuild docbuild -scheme AgoraRtmKit-Swift -derivedDataPath /tmp/docbuild -destination '${{env.PLATFORM_IOS}}';
          xcodebuild docbuild -scheme AgoraRtmKit-Swift -derivedDataPath /tmp/docbuild -destination '${{env.PLATFORM_MACOS}}';
          mv /tmp/docbuild/Build/Products/${{env.DOCC_PATH_IOS}}/AgoraRtm.doccarchive AgoraRtm-iOS.doccarchive
          mv /tmp/docbuild/Build/Products/${{env.DOCC_PATH_MACOS}}/AgoraRtm.doccarchive AgoraRtm-macOS.doccarchive
          zip -r AgoraRtm-iOS.doccarchive.zip AgoraRtm-iOS.doccarchive
          zip -r AgoraRtm-macOS.doccarchive.zip AgoraRtm-macOS.doccarchive
      - name: Upload iOS DocC Archive
        uses: actions/upload-artifact@v3
        with:
          name: AgoraRtm-iOS.doccarchive.zip
          path: AgoraRtm-iOS.doccarchive.zip
      - name: Upload macOS DocC Archive
        uses: actions/upload-artifact@v3
        with:
          name: AgoraRtm-macOS.doccarchive.zip
          path: AgoraRtm-macOS.doccarchive.zip
      - name: Static Host iOS
        run: |
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting AgoraRtm-iOS.doccarchive \
            --hosting-base-path AgoraRtm_Apple \
            --output-path docs;
          echo "<script>window.location.href += \"/documentation/agorartm\"</script>" > docs/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload docs directory
          path: 'docs'
      - name: Upload iOS DocC Archive to GitHub release ⬆️
        if: github.event.release
        uses: svenstaro/upload-release-action@2.6.0
        with:
          file: AgoraRtm-iOS.doccarchive.zip
          asset_name: AgoraRtm-iOS.doccarchive.zip
          tag: ${{ github.ref_name }}
      - name: Upload macOS DocC Archive to GitHub release ⬆️
        if: github.event.release
        uses: svenstaro/upload-release-action@2.6.0
        with:
          file: AgoraRtm-macOS.doccarchive.zip
          asset_name: AgoraRtm-macOS.doccarchive.zip
          tag: ${{ github.ref_name }}
      - name: Deploy to GitHub Pages
        if: github.event.pusher
        id: deployment
        uses: actions/deploy-pages@v2
